import type { ObservationStation } from "./types";
import { coopsLatestWaterLevelUrl, ndbcRealtimeUrl } from "./providerLinks";

export const LEGACY_STATION_ALIASES: Record<string, string> = {
  "ndbc-bib": "ndbc:NWST2",
  "ndbc-tcd": "coops:8771013",
  "ndbc-pta": "ndbc:PTAT2",
  "ndbc-spi": "coops:8779748",
  "manual-lt": "manual-lt",
};

export const NOAA_STATIONS: ObservationStation[] = [
  {
    id: "ndbc:NWST2",
    name: "NWS Weather Station 1",
    type: "wind_station",
    latitude: 27.75,
    longitude: -96.768,
    provider: "ndbc",
    sourceLabel: "NDBC",
    rawUrl: ndbcRealtimeUrl("NWST2"),
    supportsWind: true,
    supportsWaves: true,
  },
  {
    id: "ndbc:PTAT2",
    name: "Port Aransas",
    type: "wind_station",
    latitude: 27.826,
    longitude: -97.05,
    provider: "ndbc",
    sourceLabel: "NDBC",
    rawUrl: ndbcRealtimeUrl("PTAT2"),
    supportsWind: true,
  },
  {
    id: "ndbc:GNJT2",
    name: "Galveston North Jetty",
    type: "wind_station",
    latitude: 29.357,
    longitude: -94.724,
    provider: "ndbc",
    sourceLabel: "NDBC",
    rawUrl: ndbcRealtimeUrl("GNJT2"),
    supportsWind: true,
    supportsWaves: true,
  },
  {
    id: "ndbc:SRST2",
    name: "South Padre Island",
    type: "wind_station",
    latitude: 26.067,
    longitude: -97.154,
    provider: "ndbc",
    sourceLabel: "NDBC",
    rawUrl: ndbcRealtimeUrl("SRST2"),
    supportsWind: true,
  },
  {
    id: "coops:8771013",
    name: "Eagle Point, Galveston Bay",
    type: "tide_station",
    latitude: 29.4813,
    longitude: -94.9173,
    provider: "coops",
    sourceLabel: "CO-OPS",
    rawUrl: coopsLatestWaterLevelUrl("8771013"),
    supportsWaterLevel: true,
    supportsTidePredictions: true,
  },
  {
    id: "coops:8771341",
    name: "Galveston Bay Entrance",
    type: "tide_station",
    latitude: 29.3573,
    longitude: -94.7248,
    provider: "coops",
    sourceLabel: "CO-OPS",
    rawUrl: coopsLatestWaterLevelUrl("8771341"),
    supportsWaterLevel: true,
    supportsTidePredictions: true,
  },
  {
    id: "coops:8775237",
    name: "Port Aransas",
    type: "tide_station",
    latitude: 27.8397,
    longitude: -97.0725,
    provider: "coops",
    sourceLabel: "CO-OPS",
    rawUrl: coopsLatestWaterLevelUrl("8775237"),
    supportsWaterLevel: true,
    supportsTidePredictions: true,
  },
  {
    id: "coops:8775870",
    name: "Bob Hall Pier",
    type: "tide_station",
    latitude: 27.5808,
    longitude: -97.2169,
    provider: "coops",
    sourceLabel: "CO-OPS",
    rawUrl: coopsLatestWaterLevelUrl("8775870"),
    supportsWaterLevel: true,
    supportsTidePredictions: true,
  },
  {
    id: "coops:8779748",
    name: "South Padre Island CG Station",
    type: "tide_station",
    latitude: 26.0731,
    longitude: -97.1669,
    provider: "coops",
    sourceLabel: "CO-OPS",
    rawUrl: coopsLatestWaterLevelUrl("8779748"),
    supportsWaterLevel: true,
    supportsTidePredictions: true,
  },
  {
    id: "manual-lt",
    name: "Mansfield Dam Wind",
    type: "wind_station",
    latitude: 30.39,
    longitude: -97.91,
    provider: "manual",
    sourceLabel: "Manual",
    supportsWind: true,
  },
];
